### ISSUE TITLE
Version 1.5 fails

### ISSUE THREAD

**Issue by elementalTIMING** [mattlewis92/positioning#2]
Hi,

after updating to v1.5 the call of `const position = positionElements(host, target, placement, appendToBody)` returns `true` instead of a position.

br,
Lars

**Comment by mattlewis92** [comment]
Thanks for reporting this so fast, I'm not actually able to reproduce it though, it should still return the position: https://github.com/mattlewis92/positioning/blob/master/src/positioning.ts#L177

**Comment by elementalTIMING** [comment]
> Thanks for reporting this so fast, I'm not actually able to reproduce it though, it should still return the position: https://github.com/mattlewis92/positioning/blob/master/src/positioning.ts#L177

well, this is really strange. In version 1.4 everything works fine and it returns the position. When I update it to 1.5 it just returns a simple `true` (I haven't changed anything in my code - made just the `npm update`). But when looking to your code I have no idea where it should come from. I will try to investigate more tomorrow. Hopefully I can then give you a bit more input.

**Comment by mattlewis92** [comment]
Ahh, I see it now, it's this function from the `Positioning` class that changed, I'll revert it now and publish as a major version bump instead: https://github.com/mattlewis92/positioning/blob/master/src/positioning.ts#L95

**Comment by mattlewis92** [comment]
If you update to `1.5.1` it will revert the api change, and then when you upgrade to 2.0 you can use the `positionElements` function instead (which will apply the positioning for you). Thanks for reporting! 😄

**Comment by elementalTIMING** [comment]
Perfect! Now it works great again. Thx for your support!
