### ISSUE TITLE
placementVals.find(), never return null

### ISSUE THREAD

**Issue by KrakenTyio** [mattlewis92/positioning#3]
Hi

This line is buggy, bc. `find` never return `null` value.

Its return `undefined` or `value<T>` of `T[]` array

https://github.com/mattlewis92/positioning/blob/7bafeb0a53b5f7695fa82e81a72000d70560670d/src/positioning.ts#L210

I suggest replace this line with
```ts
if (!placementVals.find(val => val.search('^' + obj) !== -1)) {
```

**Comment by mattlewis92** [comment]
Please can you send a PR to the ng-bootstrap repo, as this is just a copy of the sources from there: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/positioning.ts#L210

Thanks! 😄
